# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(654, 315)
        MainWindow.setMinimumSize(QtCore.QSize(654, 315))
        MainWindow.setMaximumSize(QtCore.QSize(654, 315))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_100 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_100.setGeometry(QtCore.QRect(10, 10, 25, 25))
        self.pushButton_100.setText("")
        self.pushButton_100.setObjectName("pushButton_100")
        self.pushButton_101 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_101.setGeometry(QtCore.QRect(40, 10, 25, 25))
        self.pushButton_101.setText("")
        self.pushButton_101.setObjectName("pushButton_101")
        self.pushButton_102 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_102.setGeometry(QtCore.QRect(70, 10, 25, 25))
        self.pushButton_102.setText("")
        self.pushButton_102.setObjectName("pushButton_102")
        self.pushButton_103 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_103.setGeometry(QtCore.QRect(100, 10, 25, 25))
        self.pushButton_103.setText("")
        self.pushButton_103.setObjectName("pushButton_103")
        self.pushButton_104 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_104.setGeometry(QtCore.QRect(130, 10, 25, 25))
        self.pushButton_104.setText("")
        self.pushButton_104.setObjectName("pushButton_104")
        self.pushButton_105 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_105.setGeometry(QtCore.QRect(160, 10, 25, 25))
        self.pushButton_105.setText("")
        self.pushButton_105.setObjectName("pushButton_105")
        self.pushButton_106 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_106.setGeometry(QtCore.QRect(190, 10, 25, 25))
        self.pushButton_106.setText("")
        self.pushButton_106.setObjectName("pushButton_106")
        self.pushButton_107 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_107.setGeometry(QtCore.QRect(220, 10, 25, 25))
        self.pushButton_107.setText("")
        self.pushButton_107.setObjectName("pushButton_107")
        self.pushButton_108 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_108.setGeometry(QtCore.QRect(250, 10, 25, 25))
        self.pushButton_108.setText("")
        self.pushButton_108.setObjectName("pushButton_108")
        self.pushButton_109 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_109.setGeometry(QtCore.QRect(280, 10, 25, 25))
        self.pushButton_109.setText("")
        self.pushButton_109.setObjectName("pushButton_109")
        self.pushButton_120 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_120.setGeometry(QtCore.QRect(10, 70, 25, 25))
        self.pushButton_120.setText("")
        self.pushButton_120.setObjectName("pushButton_120")
        self.pushButton_121 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_121.setGeometry(QtCore.QRect(40, 70, 25, 25))
        self.pushButton_121.setText("")
        self.pushButton_121.setObjectName("pushButton_121")
        self.pushButton_122 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_122.setGeometry(QtCore.QRect(70, 70, 25, 25))
        self.pushButton_122.setText("")
        self.pushButton_122.setObjectName("pushButton_122")
        self.pushButton_123 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_123.setGeometry(QtCore.QRect(100, 70, 25, 25))
        self.pushButton_123.setText("")
        self.pushButton_123.setObjectName("pushButton_123")
        self.pushButton_124 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_124.setGeometry(QtCore.QRect(130, 70, 25, 25))
        self.pushButton_124.setText("")
        self.pushButton_124.setObjectName("pushButton_124")
        self.pushButton_125 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_125.setGeometry(QtCore.QRect(160, 70, 25, 25))
        self.pushButton_125.setText("")
        self.pushButton_125.setObjectName("pushButton_125")
        self.pushButton_126 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_126.setGeometry(QtCore.QRect(190, 70, 25, 25))
        self.pushButton_126.setText("")
        self.pushButton_126.setObjectName("pushButton_126")
        self.pushButton_127 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_127.setGeometry(QtCore.QRect(220, 70, 25, 25))
        self.pushButton_127.setText("")
        self.pushButton_127.setObjectName("pushButton_127")
        self.pushButton_128 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_128.setGeometry(QtCore.QRect(250, 70, 25, 25))
        self.pushButton_128.setText("")
        self.pushButton_128.setObjectName("pushButton_128")
        self.pushButton_129 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_129.setGeometry(QtCore.QRect(280, 70, 25, 25))
        self.pushButton_129.setText("")
        self.pushButton_129.setObjectName("pushButton_129")
        self.pushButton_140 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_140.setGeometry(QtCore.QRect(10, 130, 25, 25))
        self.pushButton_140.setText("")
        self.pushButton_140.setObjectName("pushButton_140")
        self.pushButton_141 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_141.setGeometry(QtCore.QRect(40, 130, 25, 25))
        self.pushButton_141.setText("")
        self.pushButton_141.setObjectName("pushButton_141")
        self.pushButton_142 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_142.setGeometry(QtCore.QRect(70, 130, 25, 25))
        self.pushButton_142.setText("")
        self.pushButton_142.setObjectName("pushButton_142")
        self.pushButton_143 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_143.setGeometry(QtCore.QRect(100, 130, 25, 25))
        self.pushButton_143.setText("")
        self.pushButton_143.setObjectName("pushButton_143")
        self.pushButton_144 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_144.setGeometry(QtCore.QRect(130, 130, 25, 25))
        self.pushButton_144.setText("")
        self.pushButton_144.setObjectName("pushButton_144")
        self.pushButton_145 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_145.setGeometry(QtCore.QRect(160, 130, 25, 25))
        self.pushButton_145.setText("")
        self.pushButton_145.setObjectName("pushButton_145")
        self.pushButton_146 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_146.setGeometry(QtCore.QRect(190, 130, 25, 25))
        self.pushButton_146.setText("")
        self.pushButton_146.setObjectName("pushButton_146")
        self.pushButton_147 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_147.setGeometry(QtCore.QRect(220, 130, 25, 25))
        self.pushButton_147.setText("")
        self.pushButton_147.setObjectName("pushButton_147")
        self.pushButton_148 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_148.setGeometry(QtCore.QRect(250, 130, 25, 25))
        self.pushButton_148.setText("")
        self.pushButton_148.setObjectName("pushButton_148")
        self.pushButton_149 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_149.setGeometry(QtCore.QRect(280, 130, 25, 25))
        self.pushButton_149.setText("")
        self.pushButton_149.setObjectName("pushButton_149")
        self.pushButton_160 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_160.setGeometry(QtCore.QRect(10, 190, 25, 25))
        self.pushButton_160.setText("")
        self.pushButton_160.setObjectName("pushButton_160")
        self.pushButton_161 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_161.setGeometry(QtCore.QRect(40, 190, 25, 25))
        self.pushButton_161.setText("")
        self.pushButton_161.setObjectName("pushButton_161")
        self.pushButton_162 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_162.setGeometry(QtCore.QRect(70, 190, 25, 25))
        self.pushButton_162.setText("")
        self.pushButton_162.setObjectName("pushButton_162")
        self.pushButton_163 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_163.setGeometry(QtCore.QRect(100, 190, 25, 25))
        self.pushButton_163.setText("")
        self.pushButton_163.setObjectName("pushButton_163")
        self.pushButton_164 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_164.setGeometry(QtCore.QRect(130, 190, 25, 25))
        self.pushButton_164.setText("")
        self.pushButton_164.setObjectName("pushButton_164")
        self.pushButton_166 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_166.setGeometry(QtCore.QRect(190, 190, 25, 25))
        self.pushButton_166.setText("")
        self.pushButton_166.setObjectName("pushButton_166")
        self.pushButton_165 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_165.setGeometry(QtCore.QRect(160, 190, 25, 25))
        self.pushButton_165.setText("")
        self.pushButton_165.setObjectName("pushButton_165")
        self.pushButton_167 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_167.setGeometry(QtCore.QRect(220, 190, 25, 25))
        self.pushButton_167.setText("")
        self.pushButton_167.setObjectName("pushButton_167")
        self.pushButton_168 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_168.setGeometry(QtCore.QRect(250, 190, 25, 25))
        self.pushButton_168.setText("")
        self.pushButton_168.setObjectName("pushButton_168")
        self.pushButton_169 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_169.setGeometry(QtCore.QRect(280, 190, 25, 25))
        self.pushButton_169.setText("")
        self.pushButton_169.setObjectName("pushButton_169")
        self.pushButton_180 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_180.setGeometry(QtCore.QRect(10, 250, 25, 25))
        self.pushButton_180.setText("")
        self.pushButton_180.setObjectName("pushButton_180")
        self.pushButton_181 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_181.setGeometry(QtCore.QRect(40, 250, 25, 25))
        self.pushButton_181.setText("")
        self.pushButton_181.setObjectName("pushButton_181")
        self.pushButton_182 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_182.setGeometry(QtCore.QRect(70, 250, 25, 25))
        self.pushButton_182.setText("")
        self.pushButton_182.setObjectName("pushButton_182")
        self.pushButton_183 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_183.setGeometry(QtCore.QRect(100, 250, 25, 25))
        self.pushButton_183.setText("")
        self.pushButton_183.setObjectName("pushButton_183")
        self.pushButton_184 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_184.setGeometry(QtCore.QRect(130, 250, 25, 25))
        self.pushButton_184.setText("")
        self.pushButton_184.setObjectName("pushButton_184")
        self.pushButton_185 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_185.setGeometry(QtCore.QRect(160, 250, 25, 25))
        self.pushButton_185.setText("")
        self.pushButton_185.setObjectName("pushButton_185")
        self.pushButton_186 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_186.setGeometry(QtCore.QRect(190, 250, 25, 25))
        self.pushButton_186.setText("")
        self.pushButton_186.setObjectName("pushButton_186")
        self.pushButton_187 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_187.setGeometry(QtCore.QRect(220, 250, 25, 25))
        self.pushButton_187.setText("")
        self.pushButton_187.setObjectName("pushButton_187")
        self.pushButton_188 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_188.setGeometry(QtCore.QRect(250, 250, 25, 25))
        self.pushButton_188.setText("")
        self.pushButton_188.setObjectName("pushButton_188")
        self.pushButton_189 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_189.setGeometry(QtCore.QRect(280, 250, 25, 25))
        self.pushButton_189.setText("")
        self.pushButton_189.setObjectName("pushButton_189")
        self.pushButton_190 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_190.setGeometry(QtCore.QRect(10, 280, 25, 25))
        self.pushButton_190.setText("")
        self.pushButton_190.setObjectName("pushButton_190")
        self.pushButton_191 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_191.setGeometry(QtCore.QRect(40, 280, 25, 25))
        self.pushButton_191.setText("")
        self.pushButton_191.setObjectName("pushButton_191")
        self.pushButton_192 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_192.setGeometry(QtCore.QRect(70, 280, 25, 25))
        self.pushButton_192.setText("")
        self.pushButton_192.setObjectName("pushButton_192")
        self.pushButton_193 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_193.setGeometry(QtCore.QRect(100, 280, 25, 25))
        self.pushButton_193.setText("")
        self.pushButton_193.setObjectName("pushButton_193")
        self.pushButton_194 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_194.setGeometry(QtCore.QRect(130, 280, 25, 25))
        self.pushButton_194.setText("")
        self.pushButton_194.setObjectName("pushButton_194")
        self.pushButton_195 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_195.setGeometry(QtCore.QRect(160, 280, 25, 25))
        self.pushButton_195.setText("")
        self.pushButton_195.setObjectName("pushButton_195")
        self.pushButton_196 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_196.setGeometry(QtCore.QRect(190, 280, 25, 25))
        self.pushButton_196.setText("")
        self.pushButton_196.setObjectName("pushButton_196")
        self.pushButton_197 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_197.setGeometry(QtCore.QRect(220, 280, 25, 25))
        self.pushButton_197.setText("")
        self.pushButton_197.setObjectName("pushButton_197")
        self.pushButton_198 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_198.setGeometry(QtCore.QRect(250, 280, 25, 25))
        self.pushButton_198.setText("")
        self.pushButton_198.setObjectName("pushButton_198")
        self.pushButton_199 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_199.setGeometry(QtCore.QRect(280, 280, 25, 25))
        self.pushButton_199.setText("")
        self.pushButton_199.setObjectName("pushButton_199")
        self.pushButton_170 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_170.setGeometry(QtCore.QRect(10, 220, 25, 25))
        self.pushButton_170.setText("")
        self.pushButton_170.setObjectName("pushButton_170")
        self.pushButton_171 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_171.setGeometry(QtCore.QRect(40, 220, 25, 25))
        self.pushButton_171.setText("")
        self.pushButton_171.setObjectName("pushButton_171")
        self.pushButton_172 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_172.setGeometry(QtCore.QRect(70, 220, 25, 25))
        self.pushButton_172.setText("")
        self.pushButton_172.setObjectName("pushButton_172")
        self.pushButton_173 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_173.setGeometry(QtCore.QRect(100, 220, 25, 25))
        self.pushButton_173.setText("")
        self.pushButton_173.setObjectName("pushButton_173")
        self.pushButton_174 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_174.setGeometry(QtCore.QRect(130, 220, 25, 25))
        self.pushButton_174.setText("")
        self.pushButton_174.setObjectName("pushButton_174")
        self.pushButton_175 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_175.setGeometry(QtCore.QRect(160, 220, 25, 25))
        self.pushButton_175.setText("")
        self.pushButton_175.setObjectName("pushButton_175")
        self.pushButton_176 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_176.setGeometry(QtCore.QRect(190, 220, 25, 25))
        self.pushButton_176.setText("")
        self.pushButton_176.setObjectName("pushButton_176")
        self.pushButton_177 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_177.setGeometry(QtCore.QRect(220, 220, 25, 25))
        self.pushButton_177.setText("")
        self.pushButton_177.setObjectName("pushButton_177")
        self.pushButton_178 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_178.setGeometry(QtCore.QRect(250, 220, 25, 25))
        self.pushButton_178.setText("")
        self.pushButton_178.setObjectName("pushButton_178")
        self.pushButton_179 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_179.setGeometry(QtCore.QRect(280, 220, 25, 25))
        self.pushButton_179.setText("")
        self.pushButton_179.setObjectName("pushButton_179")
        self.pushButton_150 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_150.setGeometry(QtCore.QRect(10, 160, 25, 25))
        self.pushButton_150.setText("")
        self.pushButton_150.setObjectName("pushButton_150")
        self.pushButton_151 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_151.setGeometry(QtCore.QRect(40, 160, 25, 25))
        self.pushButton_151.setText("")
        self.pushButton_151.setObjectName("pushButton_151")
        self.pushButton_152 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_152.setGeometry(QtCore.QRect(70, 160, 25, 25))
        self.pushButton_152.setText("")
        self.pushButton_152.setObjectName("pushButton_152")
        self.pushButton_153 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_153.setGeometry(QtCore.QRect(100, 160, 25, 25))
        self.pushButton_153.setText("")
        self.pushButton_153.setObjectName("pushButton_153")
        self.pushButton_154 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_154.setGeometry(QtCore.QRect(130, 160, 25, 25))
        self.pushButton_154.setText("")
        self.pushButton_154.setObjectName("pushButton_154")
        self.pushButton_155 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_155.setGeometry(QtCore.QRect(160, 160, 25, 25))
        self.pushButton_155.setText("")
        self.pushButton_155.setObjectName("pushButton_155")
        self.pushButton_156 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_156.setGeometry(QtCore.QRect(190, 160, 25, 25))
        self.pushButton_156.setText("")
        self.pushButton_156.setObjectName("pushButton_156")
        self.pushButton_157 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_157.setGeometry(QtCore.QRect(220, 160, 25, 25))
        self.pushButton_157.setText("")
        self.pushButton_157.setObjectName("pushButton_157")
        self.pushButton_158 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_158.setGeometry(QtCore.QRect(250, 160, 25, 25))
        self.pushButton_158.setText("")
        self.pushButton_158.setObjectName("pushButton_158")
        self.pushButton_159 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_159.setGeometry(QtCore.QRect(280, 160, 25, 25))
        self.pushButton_159.setText("")
        self.pushButton_159.setObjectName("pushButton_159")
        self.pushButton_130 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_130.setGeometry(QtCore.QRect(10, 100, 25, 25))
        self.pushButton_130.setText("")
        self.pushButton_130.setObjectName("pushButton_130")
        self.pushButton_131 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_131.setGeometry(QtCore.QRect(40, 100, 25, 25))
        self.pushButton_131.setText("")
        self.pushButton_131.setObjectName("pushButton_131")
        self.pushButton_132 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_132.setGeometry(QtCore.QRect(70, 100, 25, 25))
        self.pushButton_132.setText("")
        self.pushButton_132.setObjectName("pushButton_132")
        self.pushButton_133 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_133.setGeometry(QtCore.QRect(100, 100, 25, 25))
        self.pushButton_133.setText("")
        self.pushButton_133.setObjectName("pushButton_133")
        self.pushButton_134 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_134.setGeometry(QtCore.QRect(130, 100, 25, 25))
        self.pushButton_134.setText("")
        self.pushButton_134.setObjectName("pushButton_134")
        self.pushButton_135 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_135.setGeometry(QtCore.QRect(160, 100, 25, 25))
        self.pushButton_135.setText("")
        self.pushButton_135.setObjectName("pushButton_135")
        self.pushButton_136 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_136.setGeometry(QtCore.QRect(190, 100, 25, 25))
        self.pushButton_136.setText("")
        self.pushButton_136.setObjectName("pushButton_136")
        self.pushButton_137 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_137.setGeometry(QtCore.QRect(220, 100, 25, 25))
        self.pushButton_137.setText("")
        self.pushButton_137.setObjectName("pushButton_137")
        self.pushButton_138 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_138.setGeometry(QtCore.QRect(250, 100, 25, 25))
        self.pushButton_138.setText("")
        self.pushButton_138.setObjectName("pushButton_138")
        self.pushButton_139 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_139.setGeometry(QtCore.QRect(280, 100, 25, 25))
        self.pushButton_139.setText("")
        self.pushButton_139.setObjectName("pushButton_139")
        self.pushButton_110 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_110.setGeometry(QtCore.QRect(10, 40, 25, 25))
        self.pushButton_110.setText("")
        self.pushButton_110.setObjectName("pushButton_110")
        self.pushButton_111 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_111.setGeometry(QtCore.QRect(40, 40, 25, 25))
        self.pushButton_111.setText("")
        self.pushButton_111.setObjectName("pushButton_111")
        self.pushButton_112 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_112.setGeometry(QtCore.QRect(70, 40, 25, 25))
        self.pushButton_112.setText("")
        self.pushButton_112.setObjectName("pushButton_112")
        self.pushButton_113 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_113.setGeometry(QtCore.QRect(100, 40, 25, 25))
        self.pushButton_113.setText("")
        self.pushButton_113.setObjectName("pushButton_113")
        self.pushButton_114 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_114.setGeometry(QtCore.QRect(130, 40, 25, 25))
        self.pushButton_114.setText("")
        self.pushButton_114.setObjectName("pushButton_114")
        self.pushButton_115 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_115.setGeometry(QtCore.QRect(160, 40, 25, 25))
        self.pushButton_115.setText("")
        self.pushButton_115.setObjectName("pushButton_115")
        self.pushButton_116 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_116.setGeometry(QtCore.QRect(190, 40, 25, 25))
        self.pushButton_116.setText("")
        self.pushButton_116.setObjectName("pushButton_116")
        self.pushButton_117 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_117.setGeometry(QtCore.QRect(220, 40, 25, 25))
        self.pushButton_117.setText("")
        self.pushButton_117.setObjectName("pushButton_117")
        self.pushButton_118 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_118.setGeometry(QtCore.QRect(250, 40, 25, 25))
        self.pushButton_118.setText("")
        self.pushButton_118.setObjectName("pushButton_118")
        self.pushButton_119 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_119.setGeometry(QtCore.QRect(280, 40, 25, 25))
        self.pushButton_119.setText("")
        self.pushButton_119.setObjectName("pushButton_119")
        self.pushButton_200 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_200.setGeometry(QtCore.QRect(350, 10, 25, 25))
        self.pushButton_200.setText("")
        self.pushButton_200.setObjectName("pushButton_200")
        self.pushButton_201 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_201.setGeometry(QtCore.QRect(380, 10, 25, 25))
        self.pushButton_201.setText("")
        self.pushButton_201.setObjectName("pushButton_201")
        self.pushButton_202 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_202.setGeometry(QtCore.QRect(410, 10, 25, 25))
        self.pushButton_202.setText("")
        self.pushButton_202.setObjectName("pushButton_202")
        self.pushButton_203 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_203.setGeometry(QtCore.QRect(440, 10, 25, 25))
        self.pushButton_203.setText("")
        self.pushButton_203.setObjectName("pushButton_203")
        self.pushButton_204 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_204.setGeometry(QtCore.QRect(470, 10, 25, 25))
        self.pushButton_204.setText("")
        self.pushButton_204.setObjectName("pushButton_204")
        self.pushButton_205 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_205.setGeometry(QtCore.QRect(500, 10, 25, 25))
        self.pushButton_205.setText("")
        self.pushButton_205.setObjectName("pushButton_205")
        self.pushButton_206 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_206.setGeometry(QtCore.QRect(530, 10, 25, 25))
        self.pushButton_206.setText("")
        self.pushButton_206.setObjectName("pushButton_206")
        self.pushButton_207 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_207.setGeometry(QtCore.QRect(560, 10, 25, 25))
        self.pushButton_207.setText("")
        self.pushButton_207.setObjectName("pushButton_207")
        self.pushButton_208 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_208.setGeometry(QtCore.QRect(590, 10, 25, 25))
        self.pushButton_208.setText("")
        self.pushButton_208.setObjectName("pushButton_208")
        self.pushButton_209 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_209.setGeometry(QtCore.QRect(620, 10, 25, 25))
        self.pushButton_209.setText("")
        self.pushButton_209.setObjectName("pushButton_209")
        self.pushButton_210 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_210.setGeometry(QtCore.QRect(350, 40, 25, 25))
        self.pushButton_210.setText("")
        self.pushButton_210.setObjectName("pushButton_210")
        self.pushButton_211 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_211.setGeometry(QtCore.QRect(380, 40, 25, 25))
        self.pushButton_211.setText("")
        self.pushButton_211.setObjectName("pushButton_211")
        self.pushButton_212 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_212.setGeometry(QtCore.QRect(410, 40, 25, 25))
        self.pushButton_212.setText("")
        self.pushButton_212.setObjectName("pushButton_212")
        self.pushButton_213 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_213.setGeometry(QtCore.QRect(440, 40, 25, 25))
        self.pushButton_213.setText("")
        self.pushButton_213.setObjectName("pushButton_213")
        self.pushButton_214 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_214.setGeometry(QtCore.QRect(470, 40, 25, 25))
        self.pushButton_214.setText("")
        self.pushButton_214.setObjectName("pushButton_214")
        self.pushButton_215 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_215.setGeometry(QtCore.QRect(500, 40, 25, 25))
        self.pushButton_215.setText("")
        self.pushButton_215.setObjectName("pushButton_215")
        self.pushButton_216 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_216.setGeometry(QtCore.QRect(530, 40, 25, 25))
        self.pushButton_216.setText("")
        self.pushButton_216.setObjectName("pushButton_216")
        self.pushButton_217 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_217.setGeometry(QtCore.QRect(560, 40, 25, 25))
        self.pushButton_217.setText("")
        self.pushButton_217.setObjectName("pushButton_217")
        self.pushButton_218 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_218.setGeometry(QtCore.QRect(590, 40, 25, 25))
        self.pushButton_218.setText("")
        self.pushButton_218.setObjectName("pushButton_218")
        self.pushButton_219 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_219.setGeometry(QtCore.QRect(620, 40, 25, 25))
        self.pushButton_219.setText("")
        self.pushButton_219.setObjectName("pushButton_219")
        self.pushButton_220 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_220.setGeometry(QtCore.QRect(350, 70, 25, 25))
        self.pushButton_220.setText("")
        self.pushButton_220.setObjectName("pushButton_220")
        self.pushButton_221 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_221.setGeometry(QtCore.QRect(380, 70, 25, 25))
        self.pushButton_221.setText("")
        self.pushButton_221.setObjectName("pushButton_221")
        self.pushButton_222 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_222.setGeometry(QtCore.QRect(410, 70, 25, 25))
        self.pushButton_222.setText("")
        self.pushButton_222.setObjectName("pushButton_222")
        self.pushButton_223 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_223.setGeometry(QtCore.QRect(440, 70, 25, 25))
        self.pushButton_223.setText("")
        self.pushButton_223.setObjectName("pushButton_223")
        self.pushButton_224 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_224.setGeometry(QtCore.QRect(470, 70, 25, 25))
        self.pushButton_224.setText("")
        self.pushButton_224.setObjectName("pushButton_224")
        self.pushButton_225 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_225.setGeometry(QtCore.QRect(500, 70, 25, 25))
        self.pushButton_225.setText("")
        self.pushButton_225.setObjectName("pushButton_225")
        self.pushButton_226 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_226.setGeometry(QtCore.QRect(530, 70, 25, 25))
        self.pushButton_226.setText("")
        self.pushButton_226.setObjectName("pushButton_226")
        self.pushButton_227 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_227.setGeometry(QtCore.QRect(560, 70, 25, 25))
        self.pushButton_227.setText("")
        self.pushButton_227.setObjectName("pushButton_227")
        self.pushButton_228 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_228.setGeometry(QtCore.QRect(590, 70, 25, 25))
        self.pushButton_228.setText("")
        self.pushButton_228.setObjectName("pushButton_228")
        self.pushButton_229 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_229.setGeometry(QtCore.QRect(620, 70, 25, 25))
        self.pushButton_229.setText("")
        self.pushButton_229.setObjectName("pushButton_229")
        self.pushButton_230 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_230.setGeometry(QtCore.QRect(350, 100, 25, 25))
        self.pushButton_230.setText("")
        self.pushButton_230.setObjectName("pushButton_230")
        self.pushButton_231 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_231.setGeometry(QtCore.QRect(380, 100, 25, 25))
        self.pushButton_231.setText("")
        self.pushButton_231.setObjectName("pushButton_231")
        self.pushButton_232 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_232.setGeometry(QtCore.QRect(410, 100, 25, 25))
        self.pushButton_232.setText("")
        self.pushButton_232.setObjectName("pushButton_232")
        self.pushButton_233 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_233.setGeometry(QtCore.QRect(440, 100, 25, 25))
        self.pushButton_233.setText("")
        self.pushButton_233.setObjectName("pushButton_233")
        self.pushButton_234 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_234.setGeometry(QtCore.QRect(470, 100, 25, 25))
        self.pushButton_234.setText("")
        self.pushButton_234.setObjectName("pushButton_234")
        self.pushButton_235 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_235.setGeometry(QtCore.QRect(500, 100, 25, 25))
        self.pushButton_235.setText("")
        self.pushButton_235.setObjectName("pushButton_235")
        self.pushButton_236 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_236.setGeometry(QtCore.QRect(530, 100, 25, 25))
        self.pushButton_236.setText("")
        self.pushButton_236.setObjectName("pushButton_236")
        self.pushButton_237 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_237.setGeometry(QtCore.QRect(560, 100, 25, 25))
        self.pushButton_237.setText("")
        self.pushButton_237.setObjectName("pushButton_237")
        self.pushButton_238 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_238.setGeometry(QtCore.QRect(590, 100, 25, 25))
        self.pushButton_238.setText("")
        self.pushButton_238.setObjectName("pushButton_238")
        self.pushButton_239 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_239.setGeometry(QtCore.QRect(620, 100, 25, 25))
        self.pushButton_239.setText("")
        self.pushButton_239.setObjectName("pushButton_239")
        self.pushButton_240 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_240.setGeometry(QtCore.QRect(350, 130, 25, 25))
        self.pushButton_240.setText("")
        self.pushButton_240.setObjectName("pushButton_240")
        self.pushButton_241 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_241.setGeometry(QtCore.QRect(380, 130, 25, 25))
        self.pushButton_241.setText("")
        self.pushButton_241.setObjectName("pushButton_241")
        self.pushButton_242 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_242.setGeometry(QtCore.QRect(410, 130, 25, 25))
        self.pushButton_242.setText("")
        self.pushButton_242.setObjectName("pushButton_242")
        self.pushButton_243 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_243.setGeometry(QtCore.QRect(440, 130, 25, 25))
        self.pushButton_243.setText("")
        self.pushButton_243.setObjectName("pushButton_243")
        self.pushButton_244 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_244.setGeometry(QtCore.QRect(470, 130, 25, 25))
        self.pushButton_244.setText("")
        self.pushButton_244.setObjectName("pushButton_244")
        self.pushButton_245 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_245.setGeometry(QtCore.QRect(500, 130, 25, 25))
        self.pushButton_245.setText("")
        self.pushButton_245.setObjectName("pushButton_245")
        self.pushButton_246 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_246.setGeometry(QtCore.QRect(530, 130, 25, 25))
        self.pushButton_246.setText("")
        self.pushButton_246.setObjectName("pushButton_246")
        self.pushButton_247 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_247.setGeometry(QtCore.QRect(560, 130, 25, 25))
        self.pushButton_247.setText("")
        self.pushButton_247.setObjectName("pushButton_247")
        self.pushButton_248 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_248.setGeometry(QtCore.QRect(590, 130, 25, 25))
        self.pushButton_248.setText("")
        self.pushButton_248.setObjectName("pushButton_248")
        self.pushButton_249 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_249.setGeometry(QtCore.QRect(620, 130, 25, 25))
        self.pushButton_249.setText("")
        self.pushButton_249.setObjectName("pushButton_249")
        self.pushButton_250 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_250.setGeometry(QtCore.QRect(350, 160, 25, 25))
        self.pushButton_250.setText("")
        self.pushButton_250.setObjectName("pushButton_250")
        self.pushButton_251 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_251.setGeometry(QtCore.QRect(380, 160, 25, 25))
        self.pushButton_251.setText("")
        self.pushButton_251.setObjectName("pushButton_251")
        self.pushButton_252 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_252.setGeometry(QtCore.QRect(410, 160, 25, 25))
        self.pushButton_252.setText("")
        self.pushButton_252.setObjectName("pushButton_252")
        self.pushButton_253 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_253.setGeometry(QtCore.QRect(440, 160, 25, 25))
        self.pushButton_253.setText("")
        self.pushButton_253.setObjectName("pushButton_253")
        self.pushButton_254 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_254.setGeometry(QtCore.QRect(470, 160, 25, 25))
        self.pushButton_254.setText("")
        self.pushButton_254.setObjectName("pushButton_254")
        self.pushButton_255 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_255.setGeometry(QtCore.QRect(500, 160, 25, 25))
        self.pushButton_255.setText("")
        self.pushButton_255.setObjectName("pushButton_255")
        self.pushButton_256 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_256.setGeometry(QtCore.QRect(530, 160, 25, 25))
        self.pushButton_256.setText("")
        self.pushButton_256.setObjectName("pushButton_256")
        self.pushButton_257 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_257.setGeometry(QtCore.QRect(560, 160, 25, 25))
        self.pushButton_257.setText("")
        self.pushButton_257.setObjectName("pushButton_257")
        self.pushButton_258 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_258.setGeometry(QtCore.QRect(590, 160, 25, 25))
        self.pushButton_258.setText("")
        self.pushButton_258.setObjectName("pushButton_258")
        self.pushButton_259 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_259.setGeometry(QtCore.QRect(620, 160, 25, 25))
        self.pushButton_259.setText("")
        self.pushButton_259.setObjectName("pushButton_259")
        self.pushButton_260 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_260.setGeometry(QtCore.QRect(350, 190, 25, 25))
        self.pushButton_260.setText("")
        self.pushButton_260.setObjectName("pushButton_260")
        self.pushButton_261 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_261.setGeometry(QtCore.QRect(380, 190, 25, 25))
        self.pushButton_261.setText("")
        self.pushButton_261.setObjectName("pushButton_261")
        self.pushButton_262 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_262.setGeometry(QtCore.QRect(410, 190, 25, 25))
        self.pushButton_262.setText("")
        self.pushButton_262.setObjectName("pushButton_262")
        self.pushButton_263 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_263.setGeometry(QtCore.QRect(440, 190, 25, 25))
        self.pushButton_263.setText("")
        self.pushButton_263.setObjectName("pushButton_263")
        self.pushButton_264 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_264.setGeometry(QtCore.QRect(470, 190, 25, 25))
        self.pushButton_264.setText("")
        self.pushButton_264.setObjectName("pushButton_264")
        self.pushButton_265 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_265.setGeometry(QtCore.QRect(500, 190, 25, 25))
        self.pushButton_265.setText("")
        self.pushButton_265.setObjectName("pushButton_265")
        self.pushButton_266 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_266.setGeometry(QtCore.QRect(530, 190, 25, 25))
        self.pushButton_266.setText("")
        self.pushButton_266.setObjectName("pushButton_266")
        self.pushButton_267 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_267.setGeometry(QtCore.QRect(560, 190, 25, 25))
        self.pushButton_267.setText("")
        self.pushButton_267.setObjectName("pushButton_267")
        self.pushButton_268 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_268.setGeometry(QtCore.QRect(590, 190, 25, 25))
        self.pushButton_268.setText("")
        self.pushButton_268.setObjectName("pushButton_268")
        self.pushButton_269 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_269.setGeometry(QtCore.QRect(620, 190, 25, 25))
        self.pushButton_269.setText("")
        self.pushButton_269.setObjectName("pushButton_269")
        self.pushButton_270 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_270.setGeometry(QtCore.QRect(350, 220, 25, 25))
        self.pushButton_270.setText("")
        self.pushButton_270.setObjectName("pushButton_270")
        self.pushButton_271 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_271.setGeometry(QtCore.QRect(380, 220, 25, 25))
        self.pushButton_271.setText("")
        self.pushButton_271.setObjectName("pushButton_271")
        self.pushButton_272 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_272.setGeometry(QtCore.QRect(410, 220, 25, 25))
        self.pushButton_272.setText("")
        self.pushButton_272.setObjectName("pushButton_272")
        self.pushButton_273 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_273.setGeometry(QtCore.QRect(440, 220, 25, 25))
        self.pushButton_273.setText("")
        self.pushButton_273.setObjectName("pushButton_273")
        self.pushButton_274 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_274.setGeometry(QtCore.QRect(470, 220, 25, 25))
        self.pushButton_274.setText("")
        self.pushButton_274.setObjectName("pushButton_274")
        self.pushButton_275 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_275.setGeometry(QtCore.QRect(500, 220, 25, 25))
        self.pushButton_275.setText("")
        self.pushButton_275.setObjectName("pushButton_275")
        self.pushButton_276 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_276.setGeometry(QtCore.QRect(530, 220, 25, 25))
        self.pushButton_276.setText("")
        self.pushButton_276.setObjectName("pushButton_276")
        self.pushButton_277 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_277.setGeometry(QtCore.QRect(560, 220, 25, 25))
        self.pushButton_277.setText("")
        self.pushButton_277.setObjectName("pushButton_277")
        self.pushButton_278 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_278.setGeometry(QtCore.QRect(590, 220, 25, 25))
        self.pushButton_278.setText("")
        self.pushButton_278.setObjectName("pushButton_278")
        self.pushButton_279 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_279.setGeometry(QtCore.QRect(620, 220, 25, 25))
        self.pushButton_279.setText("")
        self.pushButton_279.setObjectName("pushButton_279")
        self.pushButton_280 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_280.setGeometry(QtCore.QRect(350, 250, 25, 25))
        self.pushButton_280.setText("")
        self.pushButton_280.setObjectName("pushButton_280")
        self.pushButton_281 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_281.setGeometry(QtCore.QRect(380, 250, 25, 25))
        self.pushButton_281.setText("")
        self.pushButton_281.setObjectName("pushButton_281")
        self.pushButton_282 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_282.setGeometry(QtCore.QRect(410, 250, 25, 25))
        self.pushButton_282.setText("")
        self.pushButton_282.setObjectName("pushButton_282")
        self.pushButton_283 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_283.setGeometry(QtCore.QRect(440, 250, 25, 25))
        self.pushButton_283.setText("")
        self.pushButton_283.setObjectName("pushButton_283")
        self.pushButton_284 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_284.setGeometry(QtCore.QRect(470, 250, 25, 25))
        self.pushButton_284.setText("")
        self.pushButton_284.setObjectName("pushButton_284")
        self.pushButton_285 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_285.setGeometry(QtCore.QRect(500, 250, 25, 25))
        self.pushButton_285.setText("")
        self.pushButton_285.setObjectName("pushButton_285")
        self.pushButton_286 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_286.setGeometry(QtCore.QRect(530, 250, 25, 25))
        self.pushButton_286.setText("")
        self.pushButton_286.setObjectName("pushButton_286")
        self.pushButton_287 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_287.setGeometry(QtCore.QRect(560, 250, 25, 25))
        self.pushButton_287.setText("")
        self.pushButton_287.setObjectName("pushButton_287")
        self.pushButton_288 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_288.setGeometry(QtCore.QRect(590, 250, 25, 25))
        self.pushButton_288.setText("")
        self.pushButton_288.setObjectName("pushButton_288")
        self.pushButton_289 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_289.setGeometry(QtCore.QRect(620, 250, 25, 25))
        self.pushButton_289.setText("")
        self.pushButton_289.setObjectName("pushButton_289")
        self.pushButton_290 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_290.setGeometry(QtCore.QRect(350, 280, 25, 25))
        self.pushButton_290.setText("")
        self.pushButton_290.setObjectName("pushButton_290")
        self.pushButton_291 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_291.setGeometry(QtCore.QRect(380, 280, 25, 25))
        self.pushButton_291.setText("")
        self.pushButton_291.setObjectName("pushButton_291")
        self.pushButton_292 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_292.setGeometry(QtCore.QRect(410, 280, 25, 25))
        self.pushButton_292.setText("")
        self.pushButton_292.setObjectName("pushButton_292")
        self.pushButton_293 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_293.setGeometry(QtCore.QRect(440, 280, 25, 25))
        self.pushButton_293.setText("")
        self.pushButton_293.setObjectName("pushButton_293")
        self.pushButton_294 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_294.setGeometry(QtCore.QRect(470, 280, 25, 25))
        self.pushButton_294.setText("")
        self.pushButton_294.setObjectName("pushButton_294")
        self.pushButton_295 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_295.setGeometry(QtCore.QRect(500, 280, 25, 25))
        self.pushButton_295.setText("")
        self.pushButton_295.setObjectName("pushButton_295")
        self.pushButton_296 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_296.setGeometry(QtCore.QRect(530, 280, 25, 25))
        self.pushButton_296.setText("")
        self.pushButton_296.setObjectName("pushButton_296")
        self.pushButton_297 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_297.setGeometry(QtCore.QRect(560, 280, 25, 25))
        self.pushButton_297.setText("")
        self.pushButton_297.setObjectName("pushButton_297")
        self.pushButton_298 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_298.setGeometry(QtCore.QRect(590, 280, 25, 25))
        self.pushButton_298.setText("")
        self.pushButton_298.setObjectName("pushButton_298")
        self.pushButton_299 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_299.setGeometry(QtCore.QRect(620, 280, 25, 25))
        self.pushButton_299.setText("")
        self.pushButton_299.setObjectName("pushButton_299")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

